name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
          MONGODB_URL: mongodb+srv://oriolraventosc:oriolraventosc@cluster0.ltojm2e.mongodb.net/scanner-api
          SUPABASE_URL: https://qycpaqckeaalxzdpektu.supabase.co
          SUPABASE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Y3BhcWNrZWFhbHh6ZHBla3R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjgyNzcwNjIsImV4cCI6MTk4Mzg1MzA2Mn0.z5ai-ECRNRLoZ7w4HB1YLKmSyzWYTreFADdacPmfx2s
          SUPABASE_BUCKET_IMAGES: friendenemies-images
